import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hailey Emery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        {/* <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
          <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
            Header
          </p>
          <div className="fixed bottom-0 left-0 flex w-full justify-center border-t border-gray-300 bg-gradient-to-t from-zinc-200 pt-6 pb-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
            <a
              className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
            >
              Footer
            </a>
          </div>
        </div> */}
        <div className="z-10 w-full max-w-5xl items-center justify-between">
          <div className="fixed left-0 top-0 w-full flex flex-wrap justify-between border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit">
            <div className="text-lg ml-100 flex basis-full md:basis-1/12 justify-center">
              <Link href="/" className="">HE</Link>
            </div>
            <div className="flex basis-full md:basis-1/2 lg:basis-1/3 justify-around">
              <Link href="/Resume" className="text-bg"> Resume </Link>
              <Link href="/Coursework" className="text-bg"> Coursework </Link>
              <Link href="/Projects" className="text-bg"> Projects </Link>
            </div>
          </div>

          <div className="fixed left-0 bottom-0 w-full flex flex-wrap justify-evenly border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit">
            <Link href="https:www.linkedin.com/in/HaileyEmery02">LinkedIn</Link>
            <p>Hailey Emery</p>
            <Link href="https:www.github.com/HaileyEmery">Github</Link>
          </div>
          {children}
        </div>

        
      </main>          
      </body>
    </html>
  );
}
